


version: '3.8'

services:
  frontend_jarvis:
    build:
      # Change this to your local path
      context: .
      dockerfile: Dockerfile.dev
    environment:
      SPEECH_TO_TEXT_ENABLED: "true"
    ports:
    - "8080:80"
    volumes:
      - "/home/alex/Documents/Code/Docker_Projects/react_iris_website/jarvis_frontend/:src"
  