#####################################################
# Change to docker-compose.prod.yml and change any variables to your local ones
# Than run docker-compose up --build in the same directory as this file

version: '3.8'

services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jarvis_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      # Change this to your local path
      - /path/to/this/folder/db_create/db_creation.sql:/docker-entrypoint-initdb.d/db_creation.sql

      - db_jarvis:/var/lib/mysql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network
    depends_on:
      - mysql

  frontend_jarvis:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      SPEECH_TO_TEXT_ENABLED: "true"
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - redis

  backend_jarvis:
    build:
      context: ./django_backend
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: jarvis_db
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
      - frontend_jarvis

networks:
  app-network:
    driver: bridge

volumes:
  db_jarvis:

# In python use the following to access the secrets
# with open('/run/secrets/api_key', 'r') as file:
#     api_key = file.read().replace('\n', '')
