#####################################################
# Change to docker-compose.prod.yml and change any variables to your local ones
# Than run docker-compose up --build in the same directory as this file

version: '3.8'

services:

  voicestreamai:
    build:
      context: ./VoiceStreamAI
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - huggingface_models:/root/.cache/huggingface
    environment:
      PYANNOTE_AUTH_TOKEN: "VAD_TOKEN_HERE" # idk yet
      VAD_ARGS_ENV: "huggingface_token" # idk yet
      ASR_ARGS_ENV: "large-v3" # Whisper model size
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jarvis_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      # Change this to your local path
      - /path/to/this/folder/db_create/db_creation.sql:/docker-entrypoint-initdb.d/db_creation.sql
      # No need to change this
      - db_jarvis:/var/lib/mysql

  frontend_jarvis:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      SPEECH_TO_TEXT_ENABLED: "true"
    networks:
      - app-network
    volumes:
      # Change this to your local path
      - /path/to/this/folder/frontend:/change/me
    depends_on:
      - mysql
      - voicestreamai

  backend_jarvis:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: jarvis_db
    networks:
      - app-network
    volumes:
      # Change this to your local path
      - /path/to/this/folder/src:/src
    user: "1000:1000"
    depends_on:
      - mysql
      - voicestreamai
      - frontend_jarvis
    secrets:
      - db_password

networks:
  app-network:
    driver: bridge

volumes:
  db_jarvis:
  huggingface_models:

secrets:
  db_password:
    # Change this to your local path
    file: ./path/to/this/folder/docker_secrets/db_password.txt

# In python use the following to access the secrets
# with open('/run/secrets/api_key', 'r') as file:
#     api_key = file.read().replace('\n', '')
